### ISSUE TITLE
http://caautodiskont.rs/wp-admin broken php

### ISSUE THREAD

**Issue by milangru** [srtfisher/Lockdown-WPAdmin#18]
When a lock wp-admin and try to login on site with http://caautodiskont.rs/wp-admin it shows :
`Fatal error: Call to undefined function et_is_ab_testing_active() in /home/caautodi/public_html/wp-content/themes/Divi/includes/builder/framework.php on line 64`

**Comment by johncrumpton** [comment]
That's an issue with the DIVI theme
