### ISSUE TITLE
ABSPATH redefined on custom login page

### ISSUE THREAD

**Issue by jessepollak** [srtfisher/Lockdown-WPAdmin#6]
When I create a custom login page, I get a notice that `ABSPATH` has already been defined. This is because `wp-load.php` has already been required once (and `wp-login.php` requires it again).

![screenshot 2014-04-18 18 07 59](https://cloud.githubusercontent.com/assets/1097953/2747210/22e57bf2-c75f-11e3-881d-f2fb867397ab.png)

**Comment by sfai05** [comment]
Same here. How can we solve this ?

**Comment by srtfisher** [comment]
This is fixed in 121d9e25527b9cdd388447ff6469de9f7b2d747b.
