### ISSUE TITLE
Signout seems not working after install Lockdown-WPAdmin for wordpress 4.0

### ISSUE THREAD

**Issue by yangjiheng** [srtfisher/Lockdown-WPAdmin#8]
After Lockdown-WPAdmin, everything works for wordpress 4.0. Although when I try to logout, it did redirect to the login page, but user session was still in login mode. Please help fix the issue.

Thanks for the work.

**Comment by srtfisher** [comment]
Currently trying it out on 4.0.1 and I have it logging out just fine, not sure if it's because of development work though.

**Comment by AoDev** [comment]
Hello, I have the same problem on wordpress 4.1.1. Have you investigated this issue ? I can tell you more if you need it.

**Comment by srtfisher** [comment]
Working with 2.3.
